### ISSUE TITLE
Hi! Could you provide more details on the dataset for training ?

### ISSUE THREAD

**Issue by happyboy1234** [vdvchen/SGMNet#4]
Why can't I find the hdf5 file？Does the code not generate hdF5 files in the folder?

Traceback (most recent call last):
  File "dump.py", line 27, in <module>
    dataset.format_dump_data()
  File "/data5/huZhao/code/SGMNet/datadump/dumper/gl3d_train.py", line 244, in format_dump_data
    pool.map(self.format_seq,indices)
  File "/data5/huZhao/anaconda3/envs/sgmnet/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/data5/huZhao/anaconda3/envs/sgmnet/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/data5/huZhao/code/GL3D-2/dump_desc_dir/000000000000000000000009/00000010.jpg_root_1000.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by SuhZhang** [comment]
I have the same problem, how did you solve it?
Thanks. @happyboy1234

**Comment by learnmano** [comment]
Same here. Could you please tell me how to solve the problem, if you don't mind?
Thanks. @happyboy1234 @SuhZhang

**Comment by SuhZhang** [comment]
> Same here. Could you please tell me how to solve the problem, if you don't mind? Thanks. @happyboy1234 @SuhZhang

Maybe the data is missing. You should check whether the data file exists in the corresponding path.

**Comment by EATMustard** [comment]
You should change the config in gl3d.yaml, extract: "False" to "True"
