### ISSUE TITLE
if we change the two image of order, we got the different size of matching-poing, ps : config, extractor:num_kpt=300

### ISSUE THREAD

**Issue by larsoncs** [vdvchen/SGMNet#5]
thanks

**Comment by vdvchen** [comment]
Hi,

Due to the concate operation in our network, the obtained matches are expected to differ when reversing img order. However, statistically the result should make very little differences.

**Comment by larsoncs** [comment]
can you eliminate the differences?

**Comment by vdvchen** [comment]
As a workaround, you may run the network twice for both img orders and find the intersection set, as is done for some neural outlier rejector(filtering based methods)
