### ISSUE TITLE
SGMNet+SP error

### ISSUE THREAD

**Issue by 22wei22** [vdvchen/SGMNet#6]
@vdvchen 你好， 当运行SGMNet+SP时出现了一个错误，应该是因为superpoint是256维特征，但是SMGNet的权重是128维的，请问方便发送我邮箱1334637558@qq.com一个基于superpoint的SGMNet权重么？

aug_desc1, aug_desc2 = x1_pos_embedding + desc1, x2_pos_embedding + desc2
RuntimeError: The size of tensor a (128) must match the size of tensor b (256) at non-singleton dimension 1

**Comment by vdvchen** [comment]
你好
我们提供了RootSIFT/SP+SuperGlue/SGMNet的共四个weights，可以通过matching的时候传入不同config文件进行配置

**Comment by DIVE128** [comment]
> 你好 我们提供了RootSIFT/SP+SuperGlue/SGMNet的共四个weights，可以通过matching的时候传入不同config文件进行配置

用sp的SGMNet预训练模型config可以提供一下吗？还是只需要把net_channels设置为256

**Comment by vdvchen** [comment]
sp的config可以在这上面修改https://github.com/vdvchen/SGMNet/blob/52a1ebebb33b4ba952f95d239d25e600b5b8d989/evaluation/configs/eval/yfcc_eval_sgm.yaml， 把net_channels设为256, conbar设为[1,0.1], 且注意在改变点数的时候调整seed_number (随点数线性调整)
